name: very_good_blog_app_backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  dart_frog: ^1.0.0
  dart_jsonwebtoken: ^2.11.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  mongo_dart: ^0.9.1
  string_validator: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
